- name: Install and Configure Nginx
  hosts: web
  become: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present
      notify: Restart Nginx  # This runs only if Nginx is newly installed

    - name: Ensure Nginx is Running
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
        enabled: yes

  handlers:
    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted